version: 2
jobs:
  build:
    docker:
    - image: rust
    steps:
    - checkout
    - run:
        name: mkdir
        command: |
          mkdir build
          apt update
          apt install -y unzip
    - run:
        name: Prepare ghr
        command: |
          cd build
          wget -c https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
          unzip -e ghr_v0.5.4_linux_amd64.zip
          cp ./ghr /usr/local/bin
    - run:
        name: build
        command: cargo install svgbob_cli --root=build
    - run:
        name: Deploy preparation
        command: |
          mkdir deploy
          ls -R build/
          cp build/bin/svgbob deploy/
    - run:
        name: Deploy
        command: |
          ghr -replace -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME build-`date +%b-%d-%Y`-`git describe --tags` deploy
